### ISSUE TITLE
Add Enterprise Suppport

### ISSUE THREAD

**Issue by chrisschaaf** [dropseed/github-org-find-replace#1]
Hello! This is a really great tool that I came across and could definitely use right now. I see that it currently only supports the standard github URL, I was wondering if I could request or work on adding in support for enterprise instances?

Thanks!

**Comment by davegaeddert** [comment]
Hey @chrisschaaf! I probably won't work on it myself right now but I would definitely merge a PR if you get it working. I would assume that the thing to do would be to [add another option](https://github.com/dropseed/github-org-find-replace/blob/5eab546f8abe6ffb9c147b07b34cf7ebe57ae87c/main.py#L71-L74) and then use that when [setting up pygithub](https://github.com/dropseed/github-org-find-replace/blob/5eab546f8abe6ffb9c147b07b34cf7ebe57ae87c/main.py#L88) (https://github.com/PyGithub/PyGithub#simple-demo). Let me know if you run into questions.

**Comment by chrisschaaf** [comment]
Sounds good! I'll work on it as I have time, was planning to add another option for `--enterprise-base-url` and split out the `gh` assignment with a conditional. Thanks!
